const mongoose = require("mongoose");
require("dotenv").config();
const Problem = require("./models/Problem");

const csesProblems = [
  // Introductory Problems
  { title: "Weird Algorithm", difficulty: "Easy", description: "Simulate the Collatz conjecture: if n is even divide by 2, if odd multiply by 3 and add 1. Print all values until n=1.", tags: ["Simulation", "Math"], source: "CSES", timeComplexity: "O(log n)", spaceComplexity: "O(1)", hint: "Just simulate the process. No trick needed.", approach: "While n != 1: if n%2==0 print n/2 else print 3n+1. Repeat." },
  { title: "Missing Number", difficulty: "Easy", description: "Given all numbers 1 to n except one, find the missing number.", tags: ["Math", "Array"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "Sum formula: n*(n+1)/2. Subtract actual sum to get missing number.", approach: "Expected sum = n*(n+1)/2. Actual sum = sum of given array. Missing = expected - actual." },
  { title: "Repetitions", difficulty: "Easy", description: "Given a DNA string, find the longest repetition of a single character.", tags: ["String", "Greedy"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "Track current streak and max streak while scanning.", approach: "Single pass: track current char and count. When char changes, update max. Return max." },
  { title: "Increasing Array", difficulty: "Easy", description: "Make array non-decreasing with minimum number of moves (each move increases an element by 1).", tags: ["Array", "Greedy"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "Greedily increase each element to be at least as large as previous.", approach: "Scan left to right. If arr[i] < arr[i-1], add (arr[i-1]-arr[i]) to moves and set arr[i]=arr[i-1]." },
  { title: "Permutations", difficulty: "Easy", description: "Construct a permutation of 1..n such that no two adjacent elements differ by 1.", tags: ["Construction", "Array"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "Print all even numbers first, then all odd numbers.", approach: "Output: 2,4,6,...,1,3,5,... This ensures no two adjacent numbers differ by 1. Special case: n=1 output 1, n=2 no solution." },
  { title: "Number Spiral", difficulty: "Easy", description: "Given row r and column c, find the number at that position in a spiral-filled grid.", tags: ["Math", "Pattern"], source: "CSES", timeComplexity: "O(1)", spaceComplexity: "O(1)", hint: "The diagonal element at (n,n) is n^2. Work from there based on which side of diagonal you are.", approach: "Let d=max(r,c). If d is odd: if r>=c then value=d*d-(d-c), else value=d*d-(2*d-1)+(r-1). If d is even: opposite." },
  { title: "Two Knights", difficulty: "Medium", description: "Count the number of ways to place two knights on an n x n chessboard so they don't attack each other.", tags: ["Math", "Combinatorics"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "Total placements - attacking placements. Knights attack in 2x3 rectangles.", approach: "Total = C(n^2, 2). Attacking pairs = 4*(n-1)*(n-2) for each board size k from 1 to n." },
  { title: "Two Sets", difficulty: "Easy", description: "Divide numbers 1..n into two sets with equal sums.", tags: ["Math", "Greedy"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "Total sum must be even. Greedily assign numbers to sets.", approach: "If n*(n+1)/2 is odd: impossible. Else target = sum/2. Greedily pick largest numbers for set1 until target reached." },
  { title: "Bit Strings", difficulty: "Easy", description: "Count the number of bit strings of length n.", tags: ["Math", "Modular Arithmetic"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "Answer is 2^n mod 10^9+7.", approach: "Use fast modular exponentiation: result = pow(2, n, MOD)." },
  { title: "Trailing Zeros", difficulty: "Easy", description: "Count trailing zeros in n factorial.", tags: ["Math"], source: "CSES", timeComplexity: "O(log n)", spaceComplexity: "O(1)", hint: "Count factors of 5 in n!. Each pair of 2 and 5 gives a trailing zero.", approach: "ans = n/5 + n/25 + n/125 + ... until divisor > n. Factors of 2 always exceed factors of 5." },
  { title: "Tower of Hanoi", difficulty: "Easy", description: "Print the moves to solve Tower of Hanoi with n disks.", tags: ["Recursion", "Divide and Conquer"], source: "CSES", timeComplexity: "O(2^n)", spaceComplexity: "O(n)", hint: "Recursively move n-1 disks to auxiliary, move largest to target, move n-1 from auxiliary to target.", approach: "hanoi(n, from, to, aux): hanoi(n-1,from,aux,to), print move from->to, hanoi(n-1,aux,to,from). Total moves = 2^n - 1." },
  { title: "Creating Strings", difficulty: "Medium", description: "Given a string, print all distinct permutations in alphabetical order.", tags: ["Backtracking", "String", "Sorting"], source: "CSES", timeComplexity: "O(n! * n)", spaceComplexity: "O(n)", hint: "Sort string first, then use next_permutation or backtracking with visited array.", approach: "Sort characters. Use backtracking: at each position try each unused character. Skip duplicates by checking if same char was used at this position before." },
  { title: "Apple Division", difficulty: "Easy", description: "Divide n apples into two groups to minimize the difference of sums.", tags: ["Backtracking", "Brute Force"], source: "CSES", timeComplexity: "O(2^n)", spaceComplexity: "O(n)", hint: "Try all 2^n subsets. For each subset compute sum difference.", approach: "For each subset S of {1..n}: diff = |sum(S) - (totalSum - sum(S))|. Track minimum diff. n<=20 so 2^20 is feasible." },
  { title: "Gray Code", difficulty: "Medium", description: "Generate a Gray code sequence of n bits where consecutive codes differ by exactly one bit.", tags: ["Bit Manipulation", "Recursion"], source: "CSES", timeComplexity: "O(2^n)", spaceComplexity: "O(2^n)", hint: "Gray code formula: i XOR (i>>1) gives the i-th Gray code.", approach: "For i from 0 to 2^n - 1: gray[i] = i ^ (i>>1). Print as binary string. Consecutive values differ by exactly 1 bit." },
  // Sorting and Searching
  { title: "Distinct Numbers", difficulty: "Easy", description: "Count the number of distinct values in an array.", tags: ["Sorting", "Hash Set"], source: "CSES", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", hint: "Use a set or sort and count unique elements.", approach: "Insert all elements into a HashSet. Answer = set.size(). Or sort and count elements where arr[i] != arr[i-1]." },
  { title: "Apartments", difficulty: "Easy", description: "Match applicants to apartments where each applicant accepts apartments within k of their desired size.", tags: ["Sorting", "Two Pointers", "Greedy"], source: "CSES", timeComplexity: "O(n log n)", spaceComplexity: "O(1)", hint: "Sort both arrays. Use two pointers to greedily match.", approach: "Sort applicants and apartments. Two pointers: if |apt - desired| <= k, match and advance both. If apt too small, advance apt pointer. If apt too large, advance applicant pointer." },
  { title: "Ferris Wheel", difficulty: "Easy", description: "Pair children on a ferris wheel (max 2 per gondola) to minimize gondolas used.", tags: ["Sorting", "Two Pointers", "Greedy"], source: "CSES", timeComplexity: "O(n log n)", spaceComplexity: "O(1)", hint: "Sort weights. Try to pair lightest with heaviest if they fit together.", approach: "Sort. Two pointers l=0, r=n-1. If weights[l]+weights[r]<=limit: pair them, l++, r--, gondolas++. Else: r alone, r--, gondolas++." },
  { title: "Maximum Subarray Sum", difficulty: "Easy", description: "Find the maximum sum of a contiguous subarray.", tags: ["Array", "Dynamic Programming"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "Kadane's algorithm: track current sum and reset when negative.", approach: "currentSum = max(arr[i], currentSum + arr[i]). maxSum = max(maxSum, currentSum). Kadane's algorithm in single pass." },
  { title: "Stick Lengths", difficulty: "Medium", description: "Make all sticks the same length with minimum total cost (cost = sum of absolute differences).", tags: ["Sorting", "Math", "Greedy"], source: "CSES", timeComplexity: "O(n log n)", spaceComplexity: "O(1)", hint: "Optimal target length is the median. Sort and pick middle element.", approach: "Sort array. Median minimizes sum of absolute deviations. Target = arr[n/2]. Cost = sum of |arr[i] - median|." },
  { title: "Playlist", difficulty: "Medium", description: "Find the longest subarray with all distinct values (longest playlist without repeating songs).", tags: ["Sliding Window", "Hash Map"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "Sliding window: expand right, when duplicate found shrink left past previous occurrence.", approach: "HashMap stores last index of each song. Two pointers: right expands, when duplicate at index j found: left = max(left, j+1). Window = right - left + 1." },
  { title: "Towers", difficulty: "Medium", description: "Build towers by placing cubes: each cube goes on top of a tower where top cube is strictly larger. Minimize number of towers.", tags: ["Greedy", "Sorting", "Binary Search"], source: "CSES", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", hint: "Greedy: for each cube, place on tower with smallest top that is still larger than current cube.", approach: "Use multiset of tower tops. For each cube x: find smallest top > x using upper_bound. If found, replace it with x. Else create new tower. Answer = multiset size." },
  { title: "Sum of Two Values", difficulty: "Easy", description: "Find two values in array that sum to target x.", tags: ["Array", "Hash Map", "Two Pointers"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "HashMap: for each element check if (target - element) exists in map.", approach: "HashMap approach: store index of each element. For each arr[i], check if (x - arr[i]) exists in map and index != i. Return pair of indices." },
  { title: "Factory Machines", difficulty: "Medium", description: "Find minimum time for n machines (each with different production time) to produce t products.", tags: ["Binary Search", "Math"], source: "CSES", timeComplexity: "O(n log(t*max_time))", spaceComplexity: "O(1)", hint: "Binary search on answer. Check if given time T is enough: sum of floor(T/machine[i]) >= t.", approach: "Binary search on time T. For given T: products = sum(T/k[i]). If products >= t: T is feasible. Find minimum feasible T." },
  { title: "Subarray Sums I", difficulty: "Medium", description: "Count subarrays with sum exactly x (all positive numbers).", tags: ["Sliding Window", "Two Pointers"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "Since all positive, use sliding window. Shrink when sum exceeds x.", approach: "Two pointers. Expand right adding elements. When sum > x: shrink from left. When sum == x: count++, shrink left. Works because all elements positive." },
  { title: "Subarray Sums II", difficulty: "Medium", description: "Count subarrays with sum exactly x (can have negative numbers).", tags: ["Hash Map", "Prefix Sum"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "Prefix sum + HashMap. Count pairs where prefixSum[j] - prefixSum[i] = x.", approach: "HashMap stores frequency of prefix sums. For each index: count += map[prefixSum - x]. Then add prefixSum to map. Handles negatives unlike sliding window." },
  // Dynamic Programming
  { title: "Dice Combinations", difficulty: "Easy", description: "Count ways to make sum n by throwing a dice (values 1-6). Answer mod 10^9+7.", tags: ["Dynamic Programming"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "dp[i] = sum of dp[i-1] + dp[i-2] + ... + dp[i-6].", approach: "dp[0]=1 (base). For i from 1 to n: dp[i] = sum(dp[i-j]) for j=1..6 where i-j>=0. Answer = dp[n]." },
  { title: "Minimizing Coins", difficulty: "Easy", description: "Find minimum number of coins to make sum n.", tags: ["Dynamic Programming", "Greedy"], source: "CSES", timeComplexity: "O(n * coins)", spaceComplexity: "O(n)", hint: "Classic coin change DP. dp[i] = min coins to make sum i.", approach: "dp[0]=0, dp[i]=INF. For each i: for each coin c: dp[i] = min(dp[i], dp[i-c]+1). Answer = dp[n] or -1 if INF." },
  { title: "Coin Combinations I", difficulty: "Medium", description: "Count ordered ways to make sum n using given coins (order matters).", tags: ["Dynamic Programming"], source: "CSES", timeComplexity: "O(n * coins)", spaceComplexity: "O(n)", hint: "dp[i] = number of ways to make sum i. For each sum, try all coins.", approach: "dp[0]=1. For i from 1 to n: for each coin c: dp[i] += dp[i-c]. Order matters so iterate sums outer, coins inner." },
  { title: "Coin Combinations II", difficulty: "Medium", description: "Count unordered ways to make sum n using given coins (order doesn't matter).", tags: ["Dynamic Programming", "Knapsack"], source: "CSES", timeComplexity: "O(n * coins)", spaceComplexity: "O(n)", hint: "Unbounded knapsack. Iterate coins outer, sums inner to avoid counting permutations.", approach: "dp[0]=1. For each coin c: for i from c to n: dp[i] += dp[i-c]. Coin outer loop ensures each combination counted once." },
  { title: "Removing Digits", difficulty: "Easy", description: "Repeatedly remove a digit of n from n itself. Find minimum steps to reach 0.", tags: ["Dynamic Programming", "Greedy"], source: "CSES", timeComplexity: "O(n * 10)", spaceComplexity: "O(n)", hint: "dp[i] = min steps to reach 0 from i. For each digit d of i: dp[i] = min(dp[i], dp[i-d]+1).", approach: "dp[0]=0. For i from 1 to n: for each digit d in str(i): if d>0: dp[i] = min(dp[i], dp[i-d]+1). Answer = dp[n]." },
  { title: "Grid Paths I", difficulty: "Easy", description: "Count paths from top-left to bottom-right of n x n grid moving only right or down. Some cells are blocked.", tags: ["Dynamic Programming", "Grid"], source: "CSES", timeComplexity: "O(n^2)", spaceComplexity: "O(n^2)", hint: "dp[i][j] = paths to reach cell (i,j). dp[i][j] = dp[i-1][j] + dp[i][j-1] if not blocked.", approach: "dp[1][1]=1. For each cell: if blocked dp[i][j]=0. Else dp[i][j] = dp[i-1][j] + dp[i][j-1]. Answer = dp[n][n]." },
  { title: "Edit Distance", difficulty: "Medium", description: "Find minimum edit distance (insert, delete, replace) to convert string A to string B.", tags: ["Dynamic Programming", "String"], source: "CSES", timeComplexity: "O(n * m)", spaceComplexity: "O(n * m)", hint: "dp[i][j] = edit distance between A[0..i] and B[0..j].", approach: "dp[i][0]=i, dp[0][j]=j. If A[i]==B[j]: dp[i][j]=dp[i-1][j-1]. Else: dp[i][j] = 1 + min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1])." },
  { title: "Book Shop", difficulty: "Medium", description: "0/1 Knapsack: maximize pages read given budget and book prices/pages.", tags: ["Dynamic Programming", "Knapsack"], source: "CSES", timeComplexity: "O(n * budget)", spaceComplexity: "O(n * budget)", hint: "Classic 0/1 knapsack. dp[i][j] = max pages using first i books with budget j.", approach: "dp[i][j] = max(dp[i-1][j], dp[i-1][j-price[i]] + pages[i]). Optimize space to 1D array iterating budget backwards." },
  { title: "Increasing Subsequence", difficulty: "Medium", description: "Find the length of the longest strictly increasing subsequence.", tags: ["Dynamic Programming", "Binary Search"], source: "CSES", timeComplexity: "O(n log n)", spaceComplexity: "O(n)", hint: "Patience sorting / binary search on tails array.", approach: "Maintain tails array. For each element x: binary search for first tail >= x, replace it with x. If x > all tails, append. Length of tails = LIS length." },
  // Graph Algorithms
  { title: "Counting Rooms", difficulty: "Easy", description: "Count the number of rooms (connected components) in a grid map where '.' is floor and '#' is wall.", tags: ["Graph", "DFS", "BFS", "Grid"], source: "CSES", timeComplexity: "O(n * m)", spaceComplexity: "O(n * m)", hint: "DFS/BFS from each unvisited '.' cell. Count how many times you start a new DFS.", approach: "For each unvisited '.' cell: count++, DFS to mark all connected '.' as visited. Move in 4 directions. Answer = count." },
  { title: "Labyrinth", difficulty: "Easy", description: "Find path from A to B in a grid maze. Print the path using directions U/D/L/R.", tags: ["Graph", "BFS", "Grid"], source: "CSES", timeComplexity: "O(n * m)", spaceComplexity: "O(n * m)", hint: "BFS gives shortest path. Track parent of each cell to reconstruct path.", approach: "BFS from A. Store parent[cell] = (prev_cell, direction). When B reached, backtrack through parents to get path. Print directions." },
  { title: "Building Roads", difficulty: "Easy", description: "Find minimum roads to connect all cities (find connected components, connect them).", tags: ["Graph", "DFS", "Union Find"], source: "CSES", timeComplexity: "O(n + m)", spaceComplexity: "O(n)", hint: "Find all connected components. Need (components - 1) roads. Connect any node from each component.", approach: "DFS/BFS to find connected components. Collect one representative from each component. Answer = components-1 roads connecting representatives." },
  { title: "Shortest Routes I", difficulty: "Medium", description: "Find shortest paths from node 1 to all other nodes in a directed weighted graph.", tags: ["Graph", "Dijkstra", "Heap"], source: "CSES", timeComplexity: "O((n + m) log n)", spaceComplexity: "O(n + m)", hint: "Dijkstra's algorithm with priority queue.", approach: "Dijkstra: dist[1]=0, all others INF. Min-heap of (dist, node). Process node: for each neighbor, if dist[node]+weight < dist[neighbor]: update and push to heap." },
  { title: "Shortest Routes II", difficulty: "Medium", description: "Answer q queries: shortest path between nodes u and v in undirected weighted graph.", tags: ["Graph", "Floyd-Warshall"], source: "CSES", timeComplexity: "O(n^3 + q)", spaceComplexity: "O(n^2)", hint: "Floyd-Warshall precomputes all-pairs shortest paths in O(n^3).", approach: "dist[i][j] = direct edge or INF. For k,i,j: dist[i][j] = min(dist[i][j], dist[i][k]+dist[k][j]). Answer each query in O(1)." },
  { title: "Course Schedule", difficulty: "Medium", description: "Given course prerequisites, find a valid order to complete all courses (topological sort).", tags: ["Graph", "Topological Sort", "DFS"], source: "CSES", timeComplexity: "O(n + m)", spaceComplexity: "O(n + m)", hint: "Topological sort using DFS or Kahn's algorithm (BFS with in-degree).", approach: "Kahn's: compute in-degree of all nodes. Queue nodes with in-degree 0. Process: add to result, decrease neighbor in-degrees, add new 0-in-degree nodes. If result size < n: cycle exists." },
  { title: "Round Trip", difficulty: "Medium", description: "Find a cycle in an undirected graph. Print the cycle if it exists.", tags: ["Graph", "DFS", "Cycle Detection"], source: "CSES", timeComplexity: "O(n + m)", spaceComplexity: "O(n)", hint: "DFS with color marking: white=unvisited, gray=in-stack, black=done. Back edge to gray node = cycle.", approach: "DFS with parent tracking. If we visit an already-visited node that isn't parent: cycle found. Backtrack to reconstruct cycle path." },
  { title: "Road Reparation", difficulty: "Medium", description: "Find minimum spanning tree cost. If graph not connected, output IMPOSSIBLE.", tags: ["Graph", "MST", "Kruskal", "Union Find"], source: "CSES", timeComplexity: "O(m log m)", spaceComplexity: "O(n)", hint: "Kruskal's algorithm: sort edges by weight, add if doesn't create cycle using Union-Find.", approach: "Sort edges. Union-Find to track components. For each edge (u,v,w): if find(u)!=find(v): union them, add w to MST cost. If MST has n-1 edges: done. Else IMPOSSIBLE." },
  // Range Queries
  { title: "Static Range Sum Queries", difficulty: "Easy", description: "Answer q queries each asking for sum of elements in range [l, r].", tags: ["Prefix Sum", "Array"], source: "CSES", timeComplexity: "O(n + q)", spaceComplexity: "O(n)", hint: "Precompute prefix sums. Query answer = prefix[r] - prefix[l-1].", approach: "prefix[0]=0, prefix[i]=prefix[i-1]+arr[i]. For query [l,r]: answer = prefix[r] - prefix[l-1]. O(1) per query after O(n) preprocessing." },
  { title: "Dynamic Range Sum Queries", difficulty: "Medium", description: "Support point updates and range sum queries.", tags: ["Segment Tree", "Binary Indexed Tree"], source: "CSES", timeComplexity: "O(log n)", spaceComplexity: "O(n)", hint: "Use Fenwick Tree (BIT) or Segment Tree for O(log n) updates and queries.", approach: "Fenwick Tree: update(i, delta): add delta to position i and propagate. query(l,r): prefix(r) - prefix(l-1). Each operation O(log n)." },
  { title: "Range Xor Queries", difficulty: "Easy", description: "Answer range XOR queries using prefix XOR.", tags: ["Prefix Sum", "Bit Manipulation"], source: "CSES", timeComplexity: "O(n + q)", spaceComplexity: "O(n)", hint: "XOR has same prefix property as sum. prefix[r] XOR prefix[l-1] = XOR of range [l,r].", approach: "prefix[0]=0, prefix[i]=prefix[i-1] XOR arr[i]. Query [l,r] = prefix[r] XOR prefix[l-1]. O(1) per query." },
  // String Algorithms
  { title: "String Matching", difficulty: "Medium", description: "Count occurrences of pattern in text.", tags: ["String", "KMP", "Z-Algorithm"], source: "CSES", timeComplexity: "O(n + m)", spaceComplexity: "O(n + m)", hint: "Use KMP or Z-algorithm for O(n+m) string matching.", approach: "Z-algorithm: create string pattern+'$'+text. Z[i] = length of longest prefix of combined string matching substring starting at i. Count positions where Z[i] >= len(pattern)." },
  { title: "Finding Borders", difficulty: "Medium", description: "Find all borders of a string (prefix that is also a suffix).", tags: ["String", "KMP", "Failure Function"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "KMP failure function gives all border lengths.", approach: "Compute KMP failure function f[]. f[i] = length of longest proper prefix of s[0..i] that is also suffix. All borders: follow chain f[n-1], f[f[n-1]-1], ... until 0." },
  { title: "Longest Palindrome", difficulty: "Medium", description: "Find the longest palindromic substring.", tags: ["String", "Manacher", "Dynamic Programming"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(n)", hint: "Manacher's algorithm finds all palindromes in O(n). Or expand around center in O(n^2).", approach: "Expand around center: for each center (n centers for odd, n-1 for even length), expand while chars match. Track max length palindrome found." },
  // Mathematics
  { title: "Exponentiation", difficulty: "Easy", description: "Compute a^b mod 10^9+7 for multiple queries.", tags: ["Math", "Fast Exponentiation"], source: "CSES", timeComplexity: "O(log b)", spaceComplexity: "O(1)", hint: "Fast power: a^b = (a^(b/2))^2 if b even, a*(a^(b-1)) if b odd.", approach: "Recursive: power(a,b) = if b==0: 1. if b%2==0: x=power(a,b/2), return x*x%MOD. else: return a*power(a,b-1)%MOD. O(log b)." },
  { title: "Counting Divisors", difficulty: "Easy", description: "For each number in array, count its divisors.", tags: ["Math", "Number Theory"], source: "CSES", timeComplexity: "O(sqrt(n))", spaceComplexity: "O(1)", hint: "For each number n, iterate i from 1 to sqrt(n). If i divides n, count both i and n/i.", approach: "For each x: count=0. For i=1 to sqrt(x): if x%i==0: count += (i==x/i) ? 1 : 2. O(sqrt(x)) per number." },
  { title: "Fibonacci Numbers", difficulty: "Easy", description: "Find nth Fibonacci number mod 10^9+7.", tags: ["Math", "Dynamic Programming", "Matrix Exponentiation"], source: "CSES", timeComplexity: "O(log n)", spaceComplexity: "O(1)", hint: "Matrix exponentiation: [[1,1],[1,0]]^n gives Fibonacci numbers.", approach: "For small n: simple DP. For large n: matrix exponentiation [[1,1],[1,0]]^n. F(n) = result[0][1]. O(log n) with matrix fast power." },
  { title: "Nim Game I", difficulty: "Easy", description: "Two players take turns removing objects from heaps. Player who takes last object wins. Determine winner.", tags: ["Game Theory", "Math", "Bit Manipulation"], source: "CSES", timeComplexity: "O(n)", spaceComplexity: "O(1)", hint: "XOR of all heap sizes. If XOR != 0: first player wins. If XOR == 0: second player wins.", approach: "Compute XOR of all heap sizes. If XOR != 0: first player wins (can always make XOR=0). If XOR == 0: second player wins. This is Sprague-Grundy theorem." },
];

mongoose.connect(process.env.MONGO_URI)
  .then(async () => {
    await Problem.insertMany(csesProblems);
    const total = await Problem.countDocuments();
    console.log(`CSES problems added! Total: ${total} problems`);
    process.exit(0);
  })
  .catch(err => { console.log(err); process.exit(1); });
